config/routes.rb
Rails.application.routes.draw do
  root :to => 'top#index'
  resource :posts, only: [:show, :edit]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/graphql_api/client_common.rb
module GraphqlApi
  module ClientCommon
    extend ActiveSupport::Concern

    included do # rubocop:disable Metrics/BlockLength
      # NOTE: QUERIESという名前で、
      #       [ #{定数定義兼定数取得用のメソッド名}, #{クエリ名定数名} ]の配列 をinclude元のクラスで定義する。
      #
      # (例)
      #
      #   QUERIES = [
      #     ['index_items_query', 'INDEX'],
      #     ['create_mutation', 'CREATE']
      #   ]
      #
      # (具体例)
      #   以下の条件下では、下記のようなメソッドが定義されることになる。
      #
      #   - include元がGraphqlApi::FavoriteItemGroup::Clientクラス
      #   - QUERIES = [['index_items_query', 'INDEX']] が定義済み
      #
      #
      #   private def self.index_items_query
      #     return IndexItemsQuery if defined? IndexItemsQuery
      #
      #     const_set(:IndexItemsQuery, client.parse(GraphqlApi::FavoriteItemGroup::Query::INDEX))
      #   end

      self::QUERIES.each do |constname, queryname|
        define_singleton_method constname do
          const = constname.camelize
          return const_get(const) if const_defined? const

          const_set(const, client.parse(module_parent::Query.const_get(queryname)))
        end
        singleton_class.send(:private, constname)
      end

      class << self
        private def response(api_response, response_class: nil)
          self::Response.new(
            response_class: response_class,
            api_response: api_response
          )
        end

        private def client
          client = GraphqlApi::GraphqlBase::ClientSingleton.instance.client
          Rails.env.development? ? DebugClient.new(client) : client
        end

        class DebugClient
          def initialize(origin)
            @origin = origin
          end

          def query(*args)
            @origin.query(*args).tap { DebugSession.register_graphql_response(_1) }
          end

          def method_missing(name, *args) # rubocop:disable Style/MethodMissingSuper
            @origin.send(name, *args)
          end

          def respond_to_missing?(symbol, include_private)
            @origin.respond_to_missing?(symbol, include_private)
          end
        end
      end

      class Response
        def initialize(response_class:, api_response:)
          response_class ||= ::GraphqlApi::Response
          @response = response_class.new(api_response)
          check_response
        end

        attr_reader :response

        def check_response
          return if response.success?

          response.logger(response.errors)
        end

        def success?
          response.success?
        end
      end
    end
  end
end

app/models/graphql_api/graphql_base.rb
require 'graphql/client'
require 'graphql/client/http'
require 'singleton'

module GraphqlApi
  module GraphqlBase
    class ClientSingleton
      include Singleton
      attr_accessor :client

      def initialize
        http = GraphQL::Client::HTTP.new(Settings.api_url) do
          def headers(_context) # rubocop:disable Lint/NestedMethodDefinition
            # Optionally set any HTTP headers.
            { 'User-Agent': 'Frontend GraphQL Client' }
          end
        end
        schema = GraphQL::Client.load_schema(http)
        @client = GraphQL::Client.new(schema: schema, execute: http)
      end
    end
  end
end

app/models/graphql_api/post/client.rb
module GraphqlApi
  module Post
    class Client
      QUERIES = [
        ['posts_query','POSTS_QUERY']
      ].freeze

      include ::GraphqlApi::ClientCommon

      def self.find(id)
        query_class = posts_query
        response = client.query(query_class, variables:{id: id})
        if response.errors.blank?
          response.data.post
        end
      end
    end
  end
end

app/models/graphql_api/post/query.rb
module GraphqlApi
  module Post
    class Query
      POSTS_QUERY = <<-GRAPHQL.freeze
        query($id: ID!) {
            post(id: $id) {
              id
              title
              comments {
                id
                content
              }
            }
          }
      GRAPHQL
    end
  end
end

app/models/post.rb
class Post
  def self.client
    GraphqlApi::Post::Client
  end

  def self.find(id)
    client.find(id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def post
    # @post = Post.find(1)
    @post = "aaaaaaaaaaaaaaaaaaaaaa"
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def show
  end

  def edit
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    # @post = "aaaaaaaaaaaaaaaaaaaaaa"
    @post = Post.find("2")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/application/_post.html.haml
.col
  .card
    .card-body
      %h1.card-title  title
      %p.card-text  
        = @post
      = link_to "post" ,posts_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Web
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/posts/_post.html.haml
.col
  .card
    .card-body
      %h1.card-title  title
      %p.card-text  text
      = link_to "post" ,posts_path

app/views/posts/edit.html.haml
.form-floating
  %input.form-control{:type => "text", :value => "title"}  
  %input.form-control{:type => "textarea", :value => "textarea,textarea,textarea,textarea"}

= link_to "show" ,posts_path

app/views/posts/show.html.haml
.container
  %h1.mt-5 title 
  %p.lead
    textarea,textarea,textarea,textarea
  .media-body
    %h5.mt-0  コメント
    %p  リード文リード文リード文リード文リード文リード文リード文リード文リード文リード文リード文リード文リード文リード文リード文リード文リード文リード文リード文リード文リード文リード文リード文リード文リード文リード文リード文リード文リード文リード文リード文リード文リード文リード文リード文
    %h5.mt-0  コメント
    %p  リード文リード文リード文リード文リード文リード文リード文リード文リード文リード文リード文リード文リード文リード文リード文リード文リード文リード文リード文リード文リード文リード文リード文リード文リード文リード文リード文リード文リード文リード文リード文リード文リード文リード文リード文
= link_to "top" ,root_path

= link_to "edit" ,edit_posts_path

app/views/top/index.html.haml
hello world!

-# ÷`.row
.row.row-cols-1.row-cols-md-5.g-2
  - 17.times do |post|
    = render partial: 'application/post'